project_id = "bolidzesitkkfojdyuyg"

[functions.import-medicaments-fr]
verify_jwt = false

[functions.create-initial-users]
verify_jwt = false

[functions.fix-minister-role]
verify_jwt = false

[functions.create-demo-accounts]
verify_jwt = true

[functions.create-demo-messages]
verify_jwt = true

[functions.create-demo-professional-data]
verify_jwt = true

[functions.generate-decree-with-ai]
verify_jwt = true

[functions.create-demo-doctor]
verify_jwt = false

[functions.chat-with-iasted]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.generate-greeting-audio]
verify_jwt = true

[functions.get-knowledge-base]
verify_jwt = false
