project_id = "bolidzesitkkfojdyuyg"

[functions.create-initial-users]
verify_jwt = false

[functions.create-demo-accounts]
verify_jwt = true

[functions.create-demo-messages]
verify_jwt = true

[functions.create-demo-professional-data]
verify_jwt = true